### ISSUE TITLE
.Net MAUI on iOS fails to compile with New Relic plugin

### ISSUE THREAD

**Issue by robin-schroeder-merc** [newrelic/newrelic-maui-plugin#50] opened 2024-10-09 12:50 UTC
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

When building in VSCode for iOS, we get the following message:

PackageInspectionFailed: Failed to load Info.plist from bundle at path /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.sENDap/extracted/xxxxx.app/Frameworks/NewRelic.framework; Extra info about "/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.sENDap/extracted/xxxxx.app/Frameworks/NewRelic.framework/Info.plist": dev=16777219 ino=11385879 mode=0100644 nlink=1 uid=33 gid=33 rdev=0 size=787 atime=1728418403.000000 mtime=1728418402.000000 ctime=1644146.054893 birthtime=1644145.392530 blksize=4096 blocks=8 flags=0x0 firstBytes={length = 4, bytes = 0x62706c69} ACL=<not found> extendedAttributes=<not found> 

error MT1006: Could not install the application '/Users/xxxx/Documents/Code/xxxx-Mobile/xxxx/xxxx/bin/Debug/net8.0-ios/ios-arm64/xxxx.app' on the device 'f4931ff21xxxxxxxxxxx0a82ace51': Package Inspection Failed Error (error: 0xe8000051).
 
##Describe the problem you're encountering. 
Failed compilation

## Steps to Reproduce
Add New Relic and solution fails to compile in VSCode on a Mac. Works fine on a PC with Android.

## Expected Behavior
Successful compilation

## Relevant Logs / Console output
see above 

## Your Environment
MacBook Pro
VSCode 1.94.1
.Net MAUI extension v1.3.29
C# extension v2.50.25
XCode 15.4

**Comment by ndesai-newrelic** [comment] 2024-10-09 13:02
@robin-schroeder-merc which version of newrelic maui package are you using?

**Comment by robin-schroeder-merc** [comment] 2024-10-09 14:37
With 1.1.2 it gives the error above. With 1.1.3 the app installs, but crashes immediately after it opens. I will be actively working on this today as  it is blocking the team. I will update this post if I find anything new.

**Comment by robin-schroeder-merc** [comment] 2024-10-09 16:09
We have our .Net SDK and workloads pinned at 8.0.402

**Comment by ndesai-newrelic** [comment] 2024-10-09 16:51
@robin-schroeder-merc are you using actual device to test this?

**Comment by ndesai-newrelic** [comment] 2024-10-09 16:54
@robin-schroeder-merc are you able to reproduce on sample app?

**Comment by robin-schroeder-merc** [comment] 2024-10-09 17:05
Yes, I have two iphones, one on ios 18, another on ios 15, both have the same error. I can try on the sample app. I will get back to you momentarily.

**Comment by ndesai-newrelic** [comment] 2024-10-09 18:38
@robin-schroeder-merc i am unable to reproduce it from my side.

**Comment by robin-schroeder-merc** [comment] 2024-10-09 18:40
What version of .Net SDK and what version of the MAUI workloads are you running?

**Comment by ndesai-newrelic** [comment] 2024-10-09 18:43
dotnet version: 8.0.204
<TargetFrameworks>net8.0-android;net8.0-ios;net8.0-maccatalyst</TargetFrameworks>

**Comment by robin-schroeder-merc** [comment] 2024-10-10 16:50
We have two .Net MAUI apps that we are trying to migrate from App Center to New Relic. We have pinned both to .Net  SDK 8.0.402 and the workloads to 8.0.402. You can only pin the workloads in global.json at or after 8.0.400. ([https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-workload-sets](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-workload-sets)) When we run the iOS version of our apps without the New Relic plugin (v1.1.3), it all runs just fine. When we introduce the New Relic plugin, the app compiles, but crashes soon after it launches. The crash is not registering in the New Relic portal, but the other data (logs, etc) are being collected. 
I tried to roll back to .Net 8.0.204 (as you guys are running that version) but my MacBook has now already updated to Mac OS Sequoia and I cannot pin the workload properly. I guess our best bet now is to wait for you guys to update to 8.0.402 or later and see if you encounter the same problem? For now, I guess we need to backburner this work...

**Comment by robin-schroeder-merc** [comment] 2024-10-16 19:50
Perhaps I was being a little ambitious with the configurations, but when I remove the following interactionTracingEnabled argument, I do not experience a crash soon after startup (ios only). 
`NewRelic.MAUI.Plugin.AgentStartConfiguration agentConfig = NewRelic.MAUI.Plugin.AgentStartConfiguration(interactionTracingEnabled: true);`

changed to 

`NewRelic.MAUI.Plugin.AgentStartConfiguration agentConfig = NewRelic.MAUI.Plugin.AgentStartConfiguration();`

Thanks!

**Comment by ndesai-newrelic** [comment] 2024-10-16 19:56
@robin-schroeder-merc we disabled interactionTracing to avoid this kind of issues.

**Comment by ndesai-newrelic** [comment] 2024-10-18 14:33
@robin-schroeder-merc can I close this one now?

**Comment by sgreifeneder** [comment] 2024-10-28 14:58
@ndesai-newrelic I have the same issue with v1.1.4. App crashes right after opening it (TestFlight build), but works locally.
I'm not configuring any `AgentStartConfiguration`

**Comment by ndesai-newrelic** [comment] 2024-10-29 14:55
@sgreifeneder can you share your crash report?

**Comment by sgreifeneder** [comment] 2024-10-29 16:03
@ndesai-newrelic 
[ios_crash_report.zip](https://github.com/user-attachments/files/17559800/ios_crash_report.zip)

**Comment by sgreifeneder** [comment] 2024-11-05 07:44
@ndesai-newrelic hi, any update here? could you already check the crash report?

**Comment by robin-schroeder-merc** [comment] 2024-11-05 13:55
> @robin-schroeder-merc can I close this one now?

Yes. We are not having any issues anymore. It sounds like @sgreifeneder might be having a different issue? Our issue was resolved by removing `AgentStartConfiguration` setting.

**Comment by ndesai-newrelic** [comment] 2024-11-05 14:51
@sgreifeneder We are unable to reproduce the issue, can you share sample app ?

**Comment by sgreifeneder** [comment] 2024-11-25 07:01
I've updated a few things in my GitHub action (Xcode 16.0->16.1, dotnet version 8.0.402->8.0.x, no version pinning to 8.0.402 for maui workload anymore and added strip replacement as per https://github.com/xamarin/xamarin-macios/issues/19157).
Now it seems to be working ... maybe that info can help you finding the issue.

**Closed** 2024-12-04 02:56 UTC
Labels: bug
